version: '3.8'
services:
  stats-server:
    build: stats-server/stats-service
    image: ewm-stats-server
    container_name: ewm-stats-server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/hits
      - POSTGRES_USER=hits
      - POSTGRES_PASSWORD=hits
  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    restart: always
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=hits
      - POSTGRES_USER=hits
      - POSTGRES_PASSWORD=hits
    volumes:
      - /var/lib/postgresql/data/